[supervisord]
nodaemon=true
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid
childlogdir=/var/log/supervisor

[program:mysql]
command=/bin/bash -c "service mysql start && tail -f /dev/null"
autostart=true
autorestart=false
priority=10
stdout_logfile=/var/log/supervisor/mysql.log
stderr_logfile=/var/log/supervisor/mysql.err

[program:apache2]
command=/bin/bash -c "source /etc/apache2/envvars && /usr/sbin/apache2 -D FOREGROUND"
autostart=true
autorestart=true
priority=20
stdout_logfile=/var/log/supervisor/apache2.log
stderr_logfile=/var/log/supervisor/apache2.err

[program:ssh]
command=/usr/sbin/sshd -D
autostart=true
autorestart=true
priority=20
stdout_logfile=/var/log/supervisor/ssh.log
stderr_logfile=/var/log/supervisor/ssh.err

[program:vsftpd]
command=/usr/sbin/vsftpd /etc/vsftpd.conf
autostart=true
autorestart=true
priority=20
stdout_logfile=/var/log/supervisor/vsftpd.log
stderr_logfile=/var/log/supervisor/vsftpd.err
