listen=YES
listen_ipv6=NO
anonymous_enable=YES
local_enable=NO
write_enable=NO
no_anon_password=YES
anon_root=/srv/ftp
secure_chroot_dir=/var/run/vsftpd/empty
pam_service_name=ftp
seccomp_sandbox=NO
pasv_enable=NO
